# Generated by Django 4.0.1 on 2022-01-14 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_start', models.TimeField()),
                ('course_finish', models.TimeField()),
            ],
            options={
                'verbose_name': 'course ',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_email', models.EmailField(max_length=254)),
                ('teacher_phone', models.CharField(max_length=15)),
                ('teacher_course', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=100)),
                ('stud_email', models.EmailField(max_length=254)),
                ('stud_phone', models.CharField(max_length=15)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.course')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_hall', models.CharField(max_length=50)),
                ('place_floor', models.CharField(max_length=50)),
                ('place_teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.teacher')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='place_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.place'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.teacher'),
        ),
    ]
